version: '3'
services:
  backend:
    # platform: linux/amd64
    # build: ./backend
    # image: gest-runner-backend:linux
    image: luvpatel/gest-runner:backend-linux2
    container_name: backend
    env_file:
      - ./gest-runner-env/backend.env
    ports:
      - "5003:5003"
    networks:
      - app-network

  frontend:
    # platform: linux/amd64
    # build: ./Gesture-based-Ape-Runner-Game
    # image: gest-runner-frontend:linux
    image: luvpatel/gest-runner:frontend-linux3
    container_name: frontend
    ports:
      - "8082:8080"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5003
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
